import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  console.log('Seeding database...');

  const tenant = await prisma.tenant.upsert({
    where: { slug: 'acme' },
    update: {},
    create: {
      name: 'Acme Corp',
      slug: 'acme',
      displayName: 'Acme Corporation',
      plan: 'free',
      isActive: true,
    },
  });

  console.log(`Tenant created: ${tenant.id} (${tenant.slug})`);

  await prisma.tenantPolicy.upsert({
    where: { id: tenant.id },
    update: {},
    create: {
      tenantId: tenant.id,
    },
  });

  // Argon2id hash of "Admin123!" using identity-service's default config
  // (m=65536, t=3, p=4, keyLen=32, saltLen=16). Baked in so the seed has no
  // runtime dependency on a JS argon2 binding; regenerated by:
  //   cd apps/identity-service && go run ./cmd/hashpw "Admin123!"
  // and then pasted here. Safe to keep public — this hash protects a
  // throwaway dev account against an offline attack only.
  const ADMIN_PASSWORD_HASH =
    '$argon2id$v=19$m=65536,t=3,p=4$vhtTsexobEB+5IlL7aXKUw$Ymzq904mPDrmCgU8hF0W93iVdJLYIpGkxoUDRtJOASc';

  const adminUser = await prisma.user.upsert({
    where: { email: 'admin@acme.com' },
    // `update: { passwordHash }` so re-running the seed on an existing
    // database backfills the password without otherwise touching the row.
    // Without this, anyone who seeded before this change still has a
    // null passwordHash and can't sign in.
    update: { passwordHash: ADMIN_PASSWORD_HASH },
    create: {
      email: 'admin@acme.com',
      emailVerified: true,
      displayName: 'Admin User',
      firstName: 'Admin',
      lastName: 'User',
      status: 'active',
      passwordHash: ADMIN_PASSWORD_HASH,
    },
  });

  console.log(`User created: ${adminUser.id} (${adminUser.email})`);

  const membership = await prisma.membership.upsert({
    where: {
      tenantId_userId: {
        tenantId: tenant.id,
        userId: adminUser.id,
      },
    },
    update: {},
    create: {
      tenantId: tenant.id,
      userId: adminUser.id,
      role: 'owner',
      joinedAt: new Date(),
    },
  });

  console.log(`Membership created: ${membership.id} (role: ${membership.role})`);
  console.log('Seeding complete.');
}

main()
  .catch((e) => {
    console.error('Seed error:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
